[phases.setup]
nixPkgs = ["...", "chromium"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "uvicorn contact_scraper:app --host 0.0.0.0 --port $PORT"
